### ISSUE TITLE
[DM Request]: Add enum values to dataset_type

### ISSUE THREAD

**Issue by kwittmeyer** [ranchobiosciences/Data_Modeling_Issues_Templates#1]
### Contact Details

joey@datamodel.com

### Description of changes

I would like to add the following values to dataset_type: single cell rna-seq, paired tumor-normal sequencing, and whole genome sequencing

**Comment by kwittmeyer** [comment]
Hello please see the proposed changes in issue #2 that address your request, if they look please approve the changes.

thanks
DM Team

**Comment by hillan141** [comment]
@kwittmeyer - FWIW confirming I got this trial issue, if I was a stakeholder for this issue then I guess I could comment here on the proposed changes.
