### ISSUE TITLE
[DM Request]: add enum values to dataset

### ISSUE THREAD

**Issue by kwittmeyer** [ranchobiosciences/Data_Modeling_Issues_Templates#10]
### Contact Details

joey@datamodel.com

### Description of changes

I would like to add the following values to dataset_type: single cell rna-seq, paired tumor-normal sequencing, and whole genome sequencing

**Comment by kwittmeyer** [comment]
Here are the proposed updates:
[dictionary.xlsx](https://github.com/ranchobiosciences/Data_Modeling_Issues_Templates/files/9990933/dictionary.xlsx)

**Comment by akls** [comment]
Second comment to read from python
