### ISSUE TITLE
[DM Request]: Example2 file in original request

### ISSUE THREAD

**Issue by kwittmeyer** [ranchobiosciences/Data_Modeling_Issues_Templates#11]
### Contact Details

joey@datamodel.com

### Description of changes

Here are the requested updates:
[dictionary.xlsx](https://github.com/ranchobiosciences/Data_Modeling_Issues_Templates/files/9990964/dictionary.xlsx)

**Comment by max-kastsiuchenka-ranchobiosciences** [comment]
NEW TESTING COMMENT 123

**Comment by max-kastsiuchenka-ranchobiosciences** [comment]
NEW TESTING COMMENT 123
