### ISSUE TITLE
[Model Update]: Updated workbook template to include dependencies

### ISSUE THREAD

**Issue by AJTDaedalus** [ranchobiosciences/Data_Modeling_Issues_Templates#13]
### Request Issue

13

### Description of changes

Old Entity:
New Entity:
Old Attribute:
New Attribute:
Enums:
-
-
-
...
Action: (add|delete|name change)
[dictionary.xlsx](https://github.com/ranchobiosciences/Data_Modeling_Issues_Templates/files/10059983/dictionary.xlsx)

**Comment by max-kastsiuchenka-ranchobiosciences** [comment]
NEW TESTING COMMENT 123
