### ISSUE TITLE
[DM Request]: Use me to test Workbook Invalid (file format)

### ISSUE THREAD

**Issue by kwittmeyer** [ranchobiosciences/Data_Modeling_Issues_Templates#48]
### Contact Details

joey@datamodel.com

### Description of changes

[wrong_file_format.csv](https://github.com/ranchobiosciences/Data_Modeling_Issues_Templates/files/10460352/wrong_file_format.csv)

**Comment by max-kastsiuchenka-ranchobiosciences** [comment]
comment
